# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'minis' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for minis

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  
  # add the Firebase pod for Google Authentication
  pod 'Firebase/Auth'

  target 'minisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'minisUITests' do
    # Pods for testing
  end

end
